# Generated by Django 4.2.6 on 2023-10-19 06:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('ISBN', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.IntegerField(default=0)),
                ('publisher', models.CharField(default='Unknown', max_length=255)),
                ('thumbnail', models.URLField()),
                ('ratings', models.FloatField(default=0.0)),
                ('price', models.FloatField(default=0.0)),
                ('author', models.CharField(max_length=255)),
            ],
            options={
                'db_table': "'core.book'",
            },
        ),
    ]
